FROM minio/minio:RELEASE.2025-04-22T22-12-26Z

USER 1001

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD curl -f http://localhost:9000/minio/health/live || exit 1

EXPOSE 9000 9001

CMD ["server", "/data", "--console-address", ":9001"]
