// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BookingRequest struct {
	ID        pgtype.UUID        `json:"id"`
	SlotID    pgtype.UUID        `json:"slot_id"`
	VenueID   pgtype.UUID        `json:"venue_id"`
	ArtistID  pgtype.UUID        `json:"artist_id"`
	Message   pgtype.Text        `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BusinessVerification struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TaxID              string             `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Address            string             `json:"address"`
	Phone              pgtype.Text        `json:"phone"`
	Documents          []byte             `json:"documents"`
	Status             string             `json:"status"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	ArtistID    pgtype.UUID        `json:"artist_id"`
	BookingID   pgtype.UUID        `json:"booking_id"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type NftTicket struct {
	ID              pgtype.UUID        `json:"id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	TokenID         int64              `json:"token_id"`
	ContractAddress string             `json:"contract_address"`
	TxHash          pgtype.Text        `json:"tx_hash"`
	Network         string             `json:"network"`
	TokenUri        pgtype.Text        `json:"token_uri"`
	OwnerAddress    string             `json:"owner_address"`
	IsPoap          bool               `json:"is_poap"`
	PoapClaimedAt   pgtype.Timestamptz `json:"poap_claimed_at"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	TotalAmount   int32              `json:"total_amount"`
	Status        string             `json:"status"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID           pgtype.UUID `json:"id"`
	OrderID      pgtype.UUID `json:"order_id"`
	TicketTypeID pgtype.UUID `json:"ticket_type_id"`
	Quantity     int32       `json:"quantity"`
	UnitPrice    int32       `json:"unit_price"`
	Subtotal     int32       `json:"subtotal"`
}

type Slot struct {
	ID        pgtype.UUID        `json:"id"`
	VenueID   pgtype.UUID        `json:"venue_id"`
	Date      pgtype.Date        `json:"date"`
	StartTime pgtype.Time        `json:"start_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Ticket struct {
	ID           pgtype.UUID        `json:"id"`
	OrderID      pgtype.UUID        `json:"order_id"`
	TicketTypeID pgtype.UUID        `json:"ticket_type_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	Code         string             `json:"code"`
	QrSecret     string             `json:"qr_secret"`
	Status       string             `json:"status"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TicketType struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       int32              `json:"price"`
	Quantity    int32              `json:"quantity"`
	MaxPerOrder int32              `json:"max_per_order"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID           pgtype.UUID        `json:"id"`
	OrderID      pgtype.UUID        `json:"order_id"`
	Provider     string             `json:"provider"`
	Amount       int32              `json:"amount"`
	Fee          pgtype.Int4        `json:"fee"`
	ProviderTxID pgtype.Text        `json:"provider_tx_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Venue struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Address      string             `json:"address"`
	City         string             `json:"city"`
	Capacity     int32              `json:"capacity"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	VerifiedOnly bool               `json:"verified_only"`
}

type VenueSpec struct {
	ID          pgtype.UUID        `json:"id"`
	VenueID     pgtype.UUID        `json:"venue_id"`
	Category    string             `json:"category"`
	Name        string             `json:"name"`
	Brand       pgtype.Text        `json:"brand"`
	Quantity    int32              `json:"quantity"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
