// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_slot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlotOverlap = `-- name: CheckSlotOverlap :one
SELECT COUNT(*) as cnt
FROM slots
WHERE venue_id = $1
  AND date = $2
  AND start_time < $4
  AND end_time > $3
  AND id != COALESCE($5, '00000000-0000-0000-0000-000000000000')
`

type CheckSlotOverlapParams struct {
	VenueID   pgtype.UUID `json:"venue_id"`
	Date      pgtype.Date `json:"date"`
	EndTime   pgtype.Time `json:"end_time"`
	StartTime pgtype.Time `json:"start_time"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) CheckSlotOverlap(ctx context.Context, db DBTX, arg CheckSlotOverlapParams) (int64, error) {
	row := db.QueryRow(ctx, checkSlotOverlap,
		arg.VenueID,
		arg.Date,
		arg.EndTime,
		arg.StartTime,
		arg.ID,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createSlot = `-- name: CreateSlot :one
INSERT INTO slots (id, venue_id, date, start_time, end_time, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, venue_id, date, start_time, end_time, status, created_at, updated_at
`

type CreateSlotParams struct {
	ID        pgtype.UUID `json:"id"`
	VenueID   pgtype.UUID `json:"venue_id"`
	Date      pgtype.Date `json:"date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateSlot(ctx context.Context, db DBTX, arg CreateSlotParams) (Slot, error) {
	row := db.QueryRow(ctx, createSlot,
		arg.ID,
		arg.VenueID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSlot = `-- name: DeleteSlot :exec
DELETE FROM slots WHERE id = $1
`

func (q *Queries) DeleteSlot(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteSlot, id)
	return err
}

const getSlot = `-- name: GetSlot :one
SELECT id, venue_id, date, start_time, end_time, status, created_at, updated_at
FROM slots
WHERE id = $1
`

func (q *Queries) GetSlot(ctx context.Context, db DBTX, id pgtype.UUID) (Slot, error) {
	row := db.QueryRow(ctx, getSlot, id)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableSlotsByVenue = `-- name: ListAvailableSlotsByVenue :many
SELECT id, venue_id, date, start_time, end_time, status, created_at, updated_at
FROM slots
WHERE venue_id = $1 AND status = 'available' AND date >= CURRENT_DATE
ORDER BY date, start_time
`

func (q *Queries) ListAvailableSlotsByVenue(ctx context.Context, db DBTX, venueID pgtype.UUID) ([]Slot, error) {
	rows, err := db.Query(ctx, listAvailableSlotsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByVenue = `-- name: ListSlotsByVenue :many
SELECT id, venue_id, date, start_time, end_time, status, created_at, updated_at
FROM slots
WHERE venue_id = $1
ORDER BY date, start_time
`

func (q *Queries) ListSlotsByVenue(ctx context.Context, db DBTX, venueID pgtype.UUID) ([]Slot, error) {
	rows, err := db.Query(ctx, listSlotsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Slot{}
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlotStatus = `-- name: UpdateSlotStatus :one
UPDATE slots
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, venue_id, date, start_time, end_time, status, created_at, updated_at
`

type UpdateSlotStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSlotStatus(ctx context.Context, db DBTX, arg UpdateSlotStatusParams) (Slot, error) {
	row := db.QueryRow(ctx, updateSlotStatus, arg.ID, arg.Status)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
