// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_ticket_type.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (id, event_id, name, description, price, quantity, max_per_order, sale_start_at, sale_end_at, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active', NOW(), NOW())
RETURNING id, event_id, name, description, price, quantity, max_per_order, sale_start_at, sale_end_at, status, created_at, updated_at
`

type CreateTicketTypeParams struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       int32              `json:"price"`
	Quantity    int32              `json:"quantity"`
	MaxPerOrder int32              `json:"max_per_order"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
}

func (q *Queries) CreateTicketType(ctx context.Context, db DBTX, arg CreateTicketTypeParams) (TicketType, error) {
	row := db.QueryRow(ctx, createTicketType,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
		arg.MaxPerOrder,
		arg.SaleStartAt,
		arg.SaleEndAt,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.MaxPerOrder,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTicketType = `-- name: DeleteTicketType :exec
DELETE FROM ticket_types WHERE id = $1
`

func (q *Queries) DeleteTicketType(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteTicketType, id)
	return err
}

const getTicketType = `-- name: GetTicketType :one
SELECT id, event_id, name, description, price, quantity, max_per_order, sale_start_at, sale_end_at, status, created_at, updated_at
FROM ticket_types
WHERE id = $1
`

func (q *Queries) GetTicketType(ctx context.Context, db DBTX, id pgtype.UUID) (TicketType, error) {
	row := db.QueryRow(ctx, getTicketType, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.MaxPerOrder,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketTypesByEvent = `-- name: ListTicketTypesByEvent :many
SELECT id, event_id, name, description, price, quantity, max_per_order, sale_start_at, sale_end_at, status, created_at, updated_at
FROM ticket_types
WHERE event_id = $1
ORDER BY price
`

func (q *Queries) ListTicketTypesByEvent(ctx context.Context, db DBTX, eventID pgtype.UUID) ([]TicketType, error) {
	rows, err := db.Query(ctx, listTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.MaxPerOrder,
			&i.SaleStartAt,
			&i.SaleEndAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketType = `-- name: UpdateTicketType :one
UPDATE ticket_types
SET name = $2, description = $3, price = $4, quantity = $5, max_per_order = $6, sale_start_at = $7, sale_end_at = $8, status = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, name, description, price, quantity, max_per_order, sale_start_at, sale_end_at, status, created_at, updated_at
`

type UpdateTicketTypeParams struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       int32              `json:"price"`
	Quantity    int32              `json:"quantity"`
	MaxPerOrder int32              `json:"max_per_order"`
	SaleStartAt pgtype.Timestamptz `json:"sale_start_at"`
	SaleEndAt   pgtype.Timestamptz `json:"sale_end_at"`
	Status      string             `json:"status"`
}

func (q *Queries) UpdateTicketType(ctx context.Context, db DBTX, arg UpdateTicketTypeParams) (TicketType, error) {
	row := db.QueryRow(ctx, updateTicketType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
		arg.MaxPerOrder,
		arg.SaleStartAt,
		arg.SaleEndAt,
		arg.Status,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.MaxPerOrder,
		&i.SaleStartAt,
		&i.SaleEndAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
