// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, order_id, provider, amount, fee, provider_tx_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', NOW(), NOW())
RETURNING id, order_id, provider, amount, fee, provider_tx_id, status, created_at, updated_at
`

type CreateTransactionParams struct {
	ID           pgtype.UUID `json:"id"`
	OrderID      pgtype.UUID `json:"order_id"`
	Provider     string      `json:"provider"`
	Amount       int32       `json:"amount"`
	Fee          pgtype.Int4 `json:"fee"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error) {
	row := db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.OrderID,
		arg.Provider,
		arg.Amount,
		arg.Fee,
		arg.ProviderTxID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.Amount,
		&i.Fee,
		&i.ProviderTxID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2, provider_tx_id = COALESCE($3, provider_tx_id), updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, provider, amount, fee, provider_tx_id, status, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ProviderTxID pgtype.Text `json:"provider_tx_id"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, db DBTX, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status, arg.ProviderTxID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.Amount,
		&i.Fee,
		&i.ProviderTxID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
