// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_nft.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPOAP = `-- name: ClaimPOAP :one
UPDATE nft_tickets
SET is_poap = true, poap_claimed_at = NOW(), status = 'claimed', updated_at = NOW()
WHERE ticket_id = $1 AND status = 'minted'
RETURNING id, ticket_id, token_id, contract_address, tx_hash, network, token_uri, owner_address, is_poap, poap_claimed_at, status, created_at, updated_at
`

func (q *Queries) ClaimPOAP(ctx context.Context, db DBTX, ticketID pgtype.UUID) (NftTicket, error) {
	row := db.QueryRow(ctx, claimPOAP, ticketID)
	var i NftTicket
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TokenID,
		&i.ContractAddress,
		&i.TxHash,
		&i.Network,
		&i.TokenUri,
		&i.OwnerAddress,
		&i.IsPoap,
		&i.PoapClaimedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNFTRecord = `-- name: CreateNFTRecord :one
INSERT INTO nft_tickets (id, ticket_id, token_id, contract_address, tx_hash, network, token_uri, owner_address, is_poap, poap_claimed_at, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, false, NULL, 'pending', NOW(), NOW())
RETURNING id, ticket_id, token_id, contract_address, tx_hash, network, token_uri, owner_address, is_poap, poap_claimed_at, status, created_at, updated_at
`

type CreateNFTRecordParams struct {
	ID              pgtype.UUID `json:"id"`
	TicketID        pgtype.UUID `json:"ticket_id"`
	TokenID         int64       `json:"token_id"`
	ContractAddress string      `json:"contract_address"`
	TxHash          pgtype.Text `json:"tx_hash"`
	Network         string      `json:"network"`
	TokenUri        pgtype.Text `json:"token_uri"`
	OwnerAddress    string      `json:"owner_address"`
}

func (q *Queries) CreateNFTRecord(ctx context.Context, db DBTX, arg CreateNFTRecordParams) (NftTicket, error) {
	row := db.QueryRow(ctx, createNFTRecord,
		arg.ID,
		arg.TicketID,
		arg.TokenID,
		arg.ContractAddress,
		arg.TxHash,
		arg.Network,
		arg.TokenUri,
		arg.OwnerAddress,
	)
	var i NftTicket
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TokenID,
		&i.ContractAddress,
		&i.TxHash,
		&i.Network,
		&i.TokenUri,
		&i.OwnerAddress,
		&i.IsPoap,
		&i.PoapClaimedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNFTByTicket = `-- name: GetNFTByTicket :one
SELECT id, ticket_id, token_id, contract_address, tx_hash, network, token_uri, owner_address, is_poap, poap_claimed_at, status, created_at, updated_at
FROM nft_tickets
WHERE ticket_id = $1
`

func (q *Queries) GetNFTByTicket(ctx context.Context, db DBTX, ticketID pgtype.UUID) (NftTicket, error) {
	row := db.QueryRow(ctx, getNFTByTicket, ticketID)
	var i NftTicket
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TokenID,
		&i.ContractAddress,
		&i.TxHash,
		&i.Network,
		&i.TokenUri,
		&i.OwnerAddress,
		&i.IsPoap,
		&i.PoapClaimedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNFTStatus = `-- name: UpdateNFTStatus :one
UPDATE nft_tickets
SET status = $2, tx_hash = COALESCE($3, tx_hash), token_uri = COALESCE($4, token_uri), updated_at = NOW()
WHERE id = $1
RETURNING id, ticket_id, token_id, contract_address, tx_hash, network, token_uri, owner_address, is_poap, poap_claimed_at, status, created_at, updated_at
`

type UpdateNFTStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	TxHash   pgtype.Text `json:"tx_hash"`
	TokenUri pgtype.Text `json:"token_uri"`
}

func (q *Queries) UpdateNFTStatus(ctx context.Context, db DBTX, arg UpdateNFTStatusParams) (NftTicket, error) {
	row := db.QueryRow(ctx, updateNFTStatus,
		arg.ID,
		arg.Status,
		arg.TxHash,
		arg.TokenUri,
	)
	var i NftTicket
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.TokenID,
		&i.ContractAddress,
		&i.TxHash,
		&i.Network,
		&i.TokenUri,
		&i.OwnerAddress,
		&i.IsPoap,
		&i.PoapClaimedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
