// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_ticket.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (id, order_id, ticket_type_id, event_id, code, qr_secret, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 'active', NOW())
`

type CreateTicketParams struct {
	ID           pgtype.UUID `json:"id"`
	OrderID      pgtype.UUID `json:"order_id"`
	TicketTypeID pgtype.UUID `json:"ticket_type_id"`
	EventID      pgtype.UUID `json:"event_id"`
	Code         string      `json:"code"`
	QrSecret     string      `json:"qr_secret"`
}

func (q *Queries) CreateTicket(ctx context.Context, db DBTX, arg CreateTicketParams) error {
	_, err := db.Exec(ctx, createTicket,
		arg.ID,
		arg.OrderID,
		arg.TicketTypeID,
		arg.EventID,
		arg.Code,
		arg.QrSecret,
	)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, order_id, ticket_type_id, event_id, code, qr_secret, status, used_at, created_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, db DBTX, id pgtype.UUID) (Ticket, error) {
	row := db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.EventID,
		&i.Code,
		&i.QrSecret,
		&i.Status,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketsByOrder = `-- name: ListTicketsByOrder :many
SELECT id, order_id, ticket_type_id, event_id, code, qr_secret, status, used_at, created_at
FROM tickets
WHERE order_id = $1
`

func (q *Queries) ListTicketsByOrder(ctx context.Context, db DBTX, orderID pgtype.UUID) ([]Ticket, error) {
	rows, err := db.Query(ctx, listTicketsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.EventID,
			&i.Code,
			&i.QrSecret,
			&i.Status,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUser = `-- name: ListTicketsByUser :many
SELECT t.id, t.order_id, t.ticket_type_id, t.event_id, t.code, t.qr_secret, t.status, t.used_at, t.created_at
FROM tickets t
JOIN orders o ON t.order_id = o.id
WHERE o.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTicketsByUser(ctx context.Context, db DBTX, userID pgtype.UUID) ([]Ticket, error) {
	rows, err := db.Query(ctx, listTicketsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TicketTypeID,
			&i.EventID,
			&i.Code,
			&i.QrSecret,
			&i.Status,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useTicket = `-- name: UseTicket :one
UPDATE tickets SET status = 'used', used_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, order_id, ticket_type_id, event_id, code, qr_secret, status, used_at, created_at
`

func (q *Queries) UseTicket(ctx context.Context, db DBTX, id pgtype.UUID) (Ticket, error) {
	row := db.QueryRow(ctx, useTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TicketTypeID,
		&i.EventID,
		&i.Code,
		&i.QrSecret,
		&i.Status,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
