// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, event_id, total_amount, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'pending', NOW(), NOW())
RETURNING id, user_id, event_id, total_amount, status, payment_method, paid_at, created_at, updated_at
`

type CreateOrderParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	EventID     pgtype.UUID `json:"event_id"`
	TotalAmount int32       `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, db DBTX, arg CreateOrderParams) (Order, error) {
	row := db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, event_id, total_amount, status, payment_method, paid_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, db DBTX, id pgtype.UUID) (Order, error) {
	row := db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, event_id, total_amount, status, payment_method, paid_at, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, db DBTX, userID pgtype.UUID) ([]Order, error) {
	rows, err := db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, payment_method = COALESCE($3, payment_method), paid_at = CASE WHEN $2 = 'paid' THEN NOW() ELSE paid_at END, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_id, total_amount, status, payment_method, paid_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	PaymentMethod pgtype.Text `json:"payment_method"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, db DBTX, arg UpdateOrderStatusParams) (Order, error) {
	row := db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status, arg.PaymentMethod)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
