// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking_requests (id, slot_id, venue_id, artist_id, message, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'pending', NOW(), NOW())
RETURNING id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
`

type CreateBookingParams struct {
	ID       pgtype.UUID `json:"id"`
	SlotID   pgtype.UUID `json:"slot_id"`
	VenueID  pgtype.UUID `json:"venue_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Message  pgtype.Text `json:"message"`
}

func (q *Queries) CreateBooking(ctx context.Context, db DBTX, arg CreateBookingParams) (BookingRequest, error) {
	row := db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.SlotID,
		arg.VenueID,
		arg.ArtistID,
		arg.Message,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.VenueID,
		&i.ArtistID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
FROM booking_requests
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, db DBTX, id pgtype.UUID) (BookingRequest, error) {
	row := db.QueryRow(ctx, getBooking, id)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.VenueID,
		&i.ArtistID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByArtist = `-- name: ListBookingsByArtist :many
SELECT id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
FROM booking_requests
WHERE artist_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByArtist(ctx context.Context, db DBTX, artistID pgtype.UUID) ([]BookingRequest, error) {
	rows, err := db.Query(ctx, listBookingsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingRequest{}
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.VenueID,
			&i.ArtistID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
FROM booking_requests
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByStatus(ctx context.Context, db DBTX, status string) ([]BookingRequest, error) {
	rows, err := db.Query(ctx, listBookingsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingRequest{}
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.VenueID,
			&i.ArtistID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByVenue = `-- name: ListBookingsByVenue :many
SELECT id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
FROM booking_requests
WHERE venue_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByVenue(ctx context.Context, db DBTX, venueID pgtype.UUID) ([]BookingRequest, error) {
	rows, err := db.Query(ctx, listBookingsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingRequest{}
	for rows.Next() {
		var i BookingRequest
		if err := rows.Scan(
			&i.ID,
			&i.SlotID,
			&i.VenueID,
			&i.ArtistID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE booking_requests
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slot_id, venue_id, artist_id, message, status, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, db DBTX, arg UpdateBookingStatusParams) (BookingRequest, error) {
	row := db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.SlotID,
		&i.VenueID,
		&i.ArtistID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
