// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_kyb.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusinessVerification = `-- name: CreateBusinessVerification :one
INSERT INTO business_verifications (id, user_id, business_name, tax_id, registration_number, address, phone, documents, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', NOW(), NOW())
RETURNING id, user_id, business_name, tax_id, registration_number, address, phone, documents, status, COALESCE(rejection_reason,''), verified_at, created_at, updated_at
`

type CreateBusinessVerificationParams struct {
	ID                 pgtype.UUID `json:"id"`
	UserID             pgtype.UUID `json:"user_id"`
	BusinessName       string      `json:"business_name"`
	TaxID              string      `json:"tax_id"`
	RegistrationNumber pgtype.Text `json:"registration_number"`
	Address            string      `json:"address"`
	Phone              pgtype.Text `json:"phone"`
	Documents          []byte      `json:"documents"`
}

type CreateBusinessVerificationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TaxID              string             `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Address            string             `json:"address"`
	Phone              pgtype.Text        `json:"phone"`
	Documents          []byte             `json:"documents"`
	Status             string             `json:"status"`
	RejectionReason    string             `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBusinessVerification(ctx context.Context, db DBTX, arg CreateBusinessVerificationParams) (CreateBusinessVerificationRow, error) {
	row := db.QueryRow(ctx, createBusinessVerification,
		arg.ID,
		arg.UserID,
		arg.BusinessName,
		arg.TaxID,
		arg.RegistrationNumber,
		arg.Address,
		arg.Phone,
		arg.Documents,
	)
	var i CreateBusinessVerificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Address,
		&i.Phone,
		&i.Documents,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessVerification = `-- name: GetBusinessVerification :one
SELECT id, user_id, business_name, tax_id, registration_number, address, phone, documents, status, COALESCE(rejection_reason,''), verified_at, created_at, updated_at
FROM business_verifications
WHERE user_id = $1
`

type GetBusinessVerificationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TaxID              string             `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Address            string             `json:"address"`
	Phone              pgtype.Text        `json:"phone"`
	Documents          []byte             `json:"documents"`
	Status             string             `json:"status"`
	RejectionReason    string             `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBusinessVerification(ctx context.Context, db DBTX, userID pgtype.UUID) (GetBusinessVerificationRow, error) {
	row := db.QueryRow(ctx, getBusinessVerification, userID)
	var i GetBusinessVerificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Address,
		&i.Phone,
		&i.Documents,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingVerifications = `-- name: ListPendingVerifications :many
SELECT id, user_id, business_name, tax_id, registration_number, address, phone, documents, status, COALESCE(rejection_reason,''), verified_at, created_at, updated_at
FROM business_verifications
WHERE status = 'pending'
ORDER BY created_at
`

type ListPendingVerificationsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TaxID              string             `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Address            string             `json:"address"`
	Phone              pgtype.Text        `json:"phone"`
	Documents          []byte             `json:"documents"`
	Status             string             `json:"status"`
	RejectionReason    string             `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPendingVerifications(ctx context.Context, db DBTX) ([]ListPendingVerificationsRow, error) {
	rows, err := db.Query(ctx, listPendingVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingVerificationsRow{}
	for rows.Next() {
		var i ListPendingVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessName,
			&i.TaxID,
			&i.RegistrationNumber,
			&i.Address,
			&i.Phone,
			&i.Documents,
			&i.Status,
			&i.RejectionReason,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusinessVerificationStatus = `-- name: UpdateBusinessVerificationStatus :one
UPDATE business_verifications
SET status = $2, rejection_reason = $3, verified_at = CASE WHEN $2 = 'verified' THEN NOW() ELSE verified_at END, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, business_name, tax_id, registration_number, address, phone, documents, status, COALESCE(rejection_reason,''), verified_at, created_at, updated_at
`

type UpdateBusinessVerificationStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

type UpdateBusinessVerificationStatusRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	BusinessName       string             `json:"business_name"`
	TaxID              string             `json:"tax_id"`
	RegistrationNumber pgtype.Text        `json:"registration_number"`
	Address            string             `json:"address"`
	Phone              pgtype.Text        `json:"phone"`
	Documents          []byte             `json:"documents"`
	Status             string             `json:"status"`
	RejectionReason    string             `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBusinessVerificationStatus(ctx context.Context, db DBTX, arg UpdateBusinessVerificationStatusParams) (UpdateBusinessVerificationStatusRow, error) {
	row := db.QueryRow(ctx, updateBusinessVerificationStatus, arg.ID, arg.Status, arg.RejectionReason)
	var i UpdateBusinessVerificationStatusRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessName,
		&i.TaxID,
		&i.RegistrationNumber,
		&i.Address,
		&i.Phone,
		&i.Documents,
		&i.Status,
		&i.RejectionReason,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
