// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_venue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at
`

type CreateVenueParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Address      string      `json:"address"`
	City         string      `json:"city"`
	Capacity     int32       `json:"capacity"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	ContactEmail pgtype.Text `json:"contact_email"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateVenue(ctx context.Context, db DBTX, arg CreateVenueParams) (Venue, error) {
	row := db.QueryRow(ctx, createVenue,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.City,
		arg.Capacity,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.OwnerID,
		arg.Status,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.City,
		&i.Capacity,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteVenue, id)
	return err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at
FROM venues
WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, db DBTX, id pgtype.UUID) (Venue, error) {
	row := db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.City,
		&i.Capacity,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at
FROM venues
ORDER BY created_at DESC
`

func (q *Queries) ListVenues(ctx context.Context, db DBTX) ([]Venue, error) {
	rows, err := db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.City,
			&i.Capacity,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesByOwner = `-- name: ListVenuesByOwner :many
SELECT id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at
FROM venues
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVenuesByOwner(ctx context.Context, db DBTX, ownerID pgtype.UUID) ([]Venue, error) {
	rows, err := db.Query(ctx, listVenuesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.City,
			&i.Capacity,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.OwnerID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET name = $2,
    description = $3,
    address = $4,
    city = $5,
    capacity = $6,
    contact_phone = $7,
    contact_email = $8,
    status = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, address, city, capacity, contact_phone, contact_email, owner_id, status, created_at, updated_at
`

type UpdateVenueParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Address      string      `json:"address"`
	City         string      `json:"city"`
	Capacity     int32       `json:"capacity"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	ContactEmail pgtype.Text `json:"contact_email"`
	Status       string      `json:"status"`
}

func (q *Queries) UpdateVenue(ctx context.Context, db DBTX, arg UpdateVenueParams) (Venue, error) {
	row := db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.City,
		arg.Capacity,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Status,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.City,
		&i.Capacity,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.OwnerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
