// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_venue_spec.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenueSpec = `-- name: CreateVenueSpec :one
INSERT INTO venue_specs (id, venue_id, category, name, brand, quantity, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, venue_id, category, name, brand, quantity, description, created_at, updated_at
`

type CreateVenueSpecParams struct {
	ID          pgtype.UUID `json:"id"`
	VenueID     pgtype.UUID `json:"venue_id"`
	Category    string      `json:"category"`
	Name        string      `json:"name"`
	Brand       pgtype.Text `json:"brand"`
	Quantity    int32       `json:"quantity"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateVenueSpec(ctx context.Context, db DBTX, arg CreateVenueSpecParams) (VenueSpec, error) {
	row := db.QueryRow(ctx, createVenueSpec,
		arg.ID,
		arg.VenueID,
		arg.Category,
		arg.Name,
		arg.Brand,
		arg.Quantity,
		arg.Description,
	)
	var i VenueSpec
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Category,
		&i.Name,
		&i.Brand,
		&i.Quantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenueSpec = `-- name: DeleteVenueSpec :exec
DELETE FROM venue_specs WHERE id = $1
`

func (q *Queries) DeleteVenueSpec(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteVenueSpec, id)
	return err
}

const deleteVenueSpecsByVenue = `-- name: DeleteVenueSpecsByVenue :exec
DELETE FROM venue_specs WHERE venue_id = $1
`

func (q *Queries) DeleteVenueSpecsByVenue(ctx context.Context, db DBTX, venueID pgtype.UUID) error {
	_, err := db.Exec(ctx, deleteVenueSpecsByVenue, venueID)
	return err
}

const getVenueSpec = `-- name: GetVenueSpec :one
SELECT id, venue_id, category, name, brand, quantity, description, created_at, updated_at
FROM venue_specs
WHERE id = $1
`

func (q *Queries) GetVenueSpec(ctx context.Context, db DBTX, id pgtype.UUID) (VenueSpec, error) {
	row := db.QueryRow(ctx, getVenueSpec, id)
	var i VenueSpec
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Category,
		&i.Name,
		&i.Brand,
		&i.Quantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenueSpecs = `-- name: ListVenueSpecs :many
SELECT id, venue_id, category, name, brand, quantity, description, created_at, updated_at
FROM venue_specs
WHERE venue_id = $1
ORDER BY category, name
`

func (q *Queries) ListVenueSpecs(ctx context.Context, db DBTX, venueID pgtype.UUID) ([]VenueSpec, error) {
	rows, err := db.Query(ctx, listVenueSpecs, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VenueSpec{}
	for rows.Next() {
		var i VenueSpec
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Category,
			&i.Name,
			&i.Brand,
			&i.Quantity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenueSpec = `-- name: UpdateVenueSpec :one
UPDATE venue_specs
SET category = $2,
    name = $3,
    brand = $4,
    quantity = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, venue_id, category, name, brand, quantity, description, created_at, updated_at
`

type UpdateVenueSpecParams struct {
	ID          pgtype.UUID `json:"id"`
	Category    string      `json:"category"`
	Name        string      `json:"name"`
	Brand       pgtype.Text `json:"brand"`
	Quantity    int32       `json:"quantity"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateVenueSpec(ctx context.Context, db DBTX, arg UpdateVenueSpecParams) (VenueSpec, error) {
	row := db.QueryRow(ctx, updateVenueSpec,
		arg.ID,
		arg.Category,
		arg.Name,
		arg.Brand,
		arg.Quantity,
		arg.Description,
	)
	var i VenueSpec
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Category,
		&i.Name,
		&i.Brand,
		&i.Quantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
